my_dict = {'Антон': 2006, 'Maria': 1999, 'Семен': 2010}
print('Dict:', my_dict)
print('Existing value:', my_dict.get('Антон'))
print('Not existing value:', my_dict.get('Alex','Нет'))
a = my_dict.pop('Maria')
print('Delete value:', a)
my_dict.update({'Anna': 2001, 'Саша': 2000})
print('Modified dictionary:', my_dict)
print(my_dict.keys())
print()
my_set = {1, 2, 3, 'Яблоко', 12, 30, 1, (1, 2)}
print('Set:', my_set)
my_set.add('Milk')
my_set.add(22)
my_set.remove('Яблоко')
print('Modified set:', my_set)