my_string = input("Введите строку: ")
print('Вывод количество символов введенного текста:', len(my_string))
print("Вывод в верхнем регистре:", my_string.upper())
print("Вывод в нижнем регистре:", my_string.lower())
print("Вывод без пробелов:", my_string.replace(" ", ""))
print("Вывод на экран первого символа строки:", my_string[0])
print("Вывод на экран последнего символа строки:", my_string[-1])
